---
apiVersion: v1
kind: Pod
metadata:
  name: console
  namespace: harperdb
spec:
  containers:
    - name: console
      image: curlimages/curl:8.13.0
      command:
        - sleep
        - infinity
      volumeMounts:
      - name: examples
        mountPath: /mnt/data/examples
      - name: curlrc
        mountPath: /home/curl_user/.curlrc
        subPath: .curlrc
  volumes:
    - name: examples
      configMap:
        name: examples
    - name: curlrc
      secret:
        secretName: curlrc
