---
resources:
  - resources/ConfigMap/environment.yaml
  - resources/Namespace/harperdb.yaml
  - resources/Pod/console.yaml
  - resources/Pod/harperdb.yaml
  - resources/Secret/credentials.yaml
  - resources/Secret/curlrc.yaml
  - resources/Service/api.yaml
  - resources/Service/operations-api.yaml
  - resources/Service/rest-api.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: examples
    namespace: harperdb
    files:
    - resources/ConfigMap/examples/bulk-insert-breeds-via-csv.json
    - resources/ConfigMap/examples/create-breed-table.json
    - resources/ConfigMap/examples/create-dog-table.json
    - resources/ConfigMap/examples/drop-dog-table.json
    - resources/ConfigMap/examples/insert-1-dog.json
    - resources/ConfigMap/examples/insert-multiple-dogs.json
    - resources/ConfigMap/examples/select-a-dog-by-id-using-sql.json
    - resources/ConfigMap/examples/select-dogs-and-join-breed.json
    - resources/ConfigMap/examples/update-1-dog-using-nosql.json
