---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: harperdb
spec:
  selector:
    app.kubernetes.io/name: harperdb
  ports:
  - port: 9925
    name: operations
    targetPort: 9925
  - port: 9926
    name: rest
    targetPort: 9926
