---
apiVersion: v1
kind: Service
metadata:
  name: operations-api
  namespace: harperdb
spec:
  selector:
    app.kubernetes.io/name: harperdb
  ports:
  - port: 80
    name: operations
    targetPort: 9925
