---
apiVersion: v1
kind: Secret
metadata:
  name: curlrc
  namespace: harperdb
type: Opaque
stringData:
  .curlrc: |
    fail-with-body
    location
    header "Authorization: Basic SERCX0FETUlOOnBhc3N3b3Jk"
    header "Content-Type: application/json"
    variable example@/mnt/variables/example
    url http://operations-api
    request POST
    expand-data "@/mnt/data/examples/{{example}}"
