---
apiVersion: v1
kind: Secret
metadata:
  name: curlrc
  namespace: harperdb
type: Opaque
stringData:
  .curlrc: |
    no-progress-meter
    fail-with-body
    location
    header "Authorization: Basic SERCX0FETUlOOnBhc3N3b3Jk"
    header "Content-Type: application/json"
    variable %JOB_NAME
    url http://operations-api
    request POST
    expand-data "@/mnt/data/examples/{{JOB_NAME}}.json"
